name: TODO issue proc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@master"
    - name: TODO to Issue
      uses: alstr/todo-to-issue-action@v4.4
      id: "todo"
